steps:
  - name: ":docker: Create content"
    agents:
      - "buildkite-aws-stack=*"    
    plugins:
      docker-compose#v2.6.0:
        config: .docker/docker-compose.yml
        run: enlitened-privacy

  - wait

  - name: "Commit built images"
    agents:
      - "buildkite-aws-stack=*"
    plugins:
      thedyrt/git-commit#v0.3.0:
        branch: master
